# Generated by Django 6.0 on 2025-12-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("contact_no", models.CharField(max_length=15)),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("FY", "First Year"),
                            ("SY", "Second Year"),
                            ("TY", "Third Year"),
                            ("LY", "Last Year"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("CSE", "Computer Science"),
                            ("IT", "Information Technology"),
                            ("ECE", "Electronics & Communication"),
                            ("ME", "Mechanical"),
                            ("CE", "Civil"),
                        ],
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
