# Generated by Django 6.0 on 2026-01-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_post_student_teacher_delete_studentresponse_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
