# Generated by Django 6.0 on 2026-01-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_delete_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="sports_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
